name: ci
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependency packages
      run: |
        sudo apt-get -y install libgdbm-dev libgdbm-compat-dev
    - name: make
      run: make linux
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make macos
